/** This file is auto-generated by Plasmic; please do not edit! */

import * as React from 'react';
import PlasmicLoader from '@plasmicapp/loader';

export default function PageComponent() {
    return <PlasmicLoader projectId="tPqUSAvm89CQ6Ba6P7RSnu" component="Homepage"  />
}